# commend_width: 100
# wrap_comments: true
# error_on_line_overflow: false
# error_on_line_overflow_comments: false
format_strings = true
max_width = 200 # default fine?
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
report_todo = "Always"
struct_field_align_threshold = 20
use_field_init_shorthand = true
# blank_lines_upper_bound = 2
